### ISSUE TITLE
Error 2

### ISSUE THREAD

**Issue by Mahmouded** [GordoNice/fitsgeo#1]
### >>> import fitsgeo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\fitsgeo\__init__.py", line 1, in <module>
    from .const import *
  File "C:\ProgramData\Anaconda3\lib\site-packages\fitsgeo\const.py", line 3, in <module>
    from fitsgeo.material import Material
  File "C:\ProgramData\Anaconda3\lib\site-packages\fitsgeo\material.py", line 16, in <module>
    "atomic_weight", "density", "description"])
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 686, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 452, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 936, in __init__
    self._make_engine(self.engine)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 1168, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 1998, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas\_libs\parsers.pyx", line 382, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas\_libs\parsers.pyx", line 674, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] No such file or directory: 'fitsgeo/data/PeriodicTable.dat'
>>> import pandas
>>> import fitsgeo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\fitsgeo\__init__.py", line 1, in <module>
    from .const import *
  File "C:\ProgramData\Anaconda3\lib\site-packages\fitsgeo\const.py", line 3, in <module>
    from fitsgeo.material import Material
  File "C:\ProgramData\Anaconda3\lib\site-packages\fitsgeo\material.py", line 16, in <module>
    "atomic_weight", "density", "description"])
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 686, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 452, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 936, in __init__
    self._make_engine(self.engine)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 1168, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers.py", line 1998, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas\_libs\parsers.pyx", line 382, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas\_libs\parsers.pyx", line 674, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] No such file or directory: 'fitsgeo/data/PeriodicTable.dat'

**Comment by alexmalins** [comment]
Can you confirm which version of Python and fitsgeo you have installed in your Anaconda environment? Please type `pip3 show fitsgeo` in your Anaconda prompt and reply with the output.

I think maybe you are using an old Python version (3.6 or earlier) and an old version of fitsgeo (v0.2.3) which had broken data paths.

Try using Python 3.7+ in your Anaconda environment (`conda install python=3.7`) and reinstalling fitsgeo.

**Comment by GordoNice** [comment]
> Can you confirm which version of Python and fitsgeo you have installed in your Anaconda environment? Please type `pip3 show fitsgeo` in your Anaconda prompt and reply with the output.
> 
> I think maybe you are using an old Python version (3.6 or earlier) and an old version of fitsgeo (v0.2.3) which had broken data paths.
> 
> Try using Python 3.7+ in your Anaconda environment (`conda install python=3.7`) and reinstalling fitsgeo.

Thanks for your suggestions, Alex!
Indeed, dear @Mahmouded, could you please make it more clear how fitsgeo was installed in the first place and what version of python do you have installed?

**Comment by GordoNice** [comment]
I don't see any signs of this error is still relevant. Therefore, I am going to close this issue. Dear @Mahmouded feel free to contact me again if you need help.
